### ISSUE TITLE
Using AWS keys for signing request

### ISSUE THREAD

**Issue by dberuben** [bitnami/bitnami-docker-elasticsearch-curator#5]
I'm having this issue
with the latest version:

2021-06-25 10:08:00,394 ERROR     Unable to sign AWS requests. Failed to import a module: No module named 'botocore.docs'
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.6/site-packages/elasticsearch_curator-5.8.4-py3.6.egg/curator/utils.py", line 865, in try_boto_session
  File "/opt/bitnami/python/lib/python3.6/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/opt/bitnami/python/lib/python3.6/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/session.py", line 31, in <module>
    import botocore.client
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/client.py", line 16, in <module>
    from botocore import waiter, xform_name
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
ModuleNotFoundError: No module named 'botocore.docs'

During handling of the above exception, another exception occurred:

My config:

configMaps:
  config_yml: |-
    ---
    client:
      hosts:
        - "${aws_elasticsearch_domain.es[each.key].endpoint}"
      port: 443
      # url_prefix:
      use_ssl: True
      aws_key: data.vault_generic_secret.lspay.data["es_curator_aws_key"]
      aws_secret_key: data.vault_generic_secret.lspay.data["es_curator_aws_secret_key"]
      aws_region: "${data.aws_region.current.name}"
      aws_sign_request: True
      ssl_no_validate: False
      timeout: 60
    logging:
      loglevel: INFO

**Comment by migruiz4** [comment]
Hi @dberuben,

Seems that the issue is related to the setting `aws_sign_request`.

This other issue seems to be also related: https://github.com/bitnami/bitnami-docker-elasticsearch-curator/issues/1 

In that case, the issue was resolved by re-running the following commands:
```
pip install --upgrade botocore -t /opt/bitnami/python/lib/python3.6/site-packages/
pip install --upgrade boto3 -t /opt/bitnami/python/lib/python3.6/site-packages/
```

Although the dependencies are installed in the curator `requirements.txt`, according to elasticsearch documentation that specific feature requires running the commands manually: https://www.elastic.co/guide/en/elasticsearch/client/curator/current/configfile.html#aws_sign_request

**Comment by dberuben** [comment]
Upgrading boto works, thank you
